#!/usr/bin/env python3
"""Generate asm/utils/rng_jump.inc: xoshiro256's state transition raised to
the power N, as 256 rows (one per state bit, s0 bit 0 first) of four u64
words. XORing the rows of a state's set bits advances it N steps.

Usage: rng-jump.py N > asm/utils/rng_jump.inc
"""
import sys

M = (1 << 64) - 1


def step(s):
    s0, s1, s2, s3 = s
    t = (s1 << 17) & M
    s2 ^= s0
    s3 ^= s1
    s1 ^= s2
    s0 ^= s3
    s2 ^= t
    s3 = ((s3 << 45) | (s3 >> 19)) & M
    return [s0, s1, s2, s3]


n = int(sys.argv[1])
print(f"; generated by tools/asm/rng-jump.py {n}: xoshiro256's transition")
print(f"; to the power {n}, one row of four u64 words per state bit")
for bit in range(256):
    s = [0, 0, 0, 0]
    s[bit // 64] = 1 << (bit % 64)
    for _ in range(n):
        s = step(s)
    print("    dq " + ", ".join(f"0x{w:016x}" for w in s))
